services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
  # - coturn  # uncomment if you add depends requirement
    command: ["sh", "-lc", "python app/scripts/wait_for_db.py && alembic upgrade head && uvicorn app.bootstrap.asgi:app --host 0.0.0.0 --port 8000 --reload"]
    volumes:
      - ./:/app

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: webcall
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: webcall
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  # TURN server (coturn)
  coturn:
    image: coturn/coturn:latest
    restart: unless-stopped
    command:
      - -n
      - --log-file=stdout
      - --min-port=49152
      - --max-port=49200
      - --realm=bandjshoos.ru
      - --listening-ip=0.0.0.0
      - --relay-ip=0.0.0.0
      - --listening-port=3478
      - --external-ip=104.238.24.120
      - --lt-cred-mech
      - --user=webcall:secret
      - --fingerprint
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
  - "49152-49200:49152-49200/udp"
      # Optional TLS TURN on 5349 if you configure certs
      # - "5349:5349/tcp"

volumes:
  pgdata:
  redisdata:
