services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000" # для локальной проверки, Nginx ходит на 127.0.0.1:8000
    depends_on:
      - postgres
      - redis
      - coturn
    command: ["sh", "-lc", "python app/scripts/wait_for_db.py && alembic upgrade head && uvicorn app.bootstrap.asgi:app --host 0.0.0.0 --port 8000"]
    volumes:
      - ./:/app

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: webcall
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: webcall
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redisdata:/data

  coturn:
    image: coturn/coturn:latest
    restart: unless-stopped
    command:
      - -n
      - --log-file=stdout
      - --min-port=49152
      - --max-port=49200
      - --realm=${TURN_REALM}
      - --listening-ip=0.0.0.0
      - --relay-ip=0.0.0.0
      - --listening-port=3478
      - --external-ip=${TURN_PUBLIC_IP}
      - --lt-cred-mech
      - --user=${TURN_USERNAME}:${TURN_PASSWORD}
      - --fingerprint
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
      - "49152-49200:49152-49200/udp"

volumes:
  pgdata:
  redisdata:
